### ISSUE TITLE
How to install gadget on Windows platform ?

### ISSUE THREAD

**Issue by djkormo** [kinvolk/inspektor-gadget#135]
kubectl krew install gadget

Installing plugin: gadget
W0910 14:56:39.261711   29072 install.go:164] failed to install plugin "gadget": plugin "gadget" does not offer installation for this platform
F0910 14:56:39.279711   29072 root.go:79] failed to install some plugins: [gadget]: plugin "gadget" does not offer installation for this platform
exit status 255

**Comment by mauriciovasquezbernal** [comment]
Hi @djkormo, we haven't added support for installing Inspektor Gadget on Windows machines using krew yet.

I just pushed a commit to https://github.com/kinvolk/inspektor-gadget/tree/mauricio/add-windows-binary containing some changes to compile and upload the windows binary. I don't have access to a Windows machine now, could you try to install it manually (you can download the compiled binary from https://github.com/kinvolk/inspektor-gadget/actions/runs/256682437)?

If everything works fine I'd open a PR to add this to the krew installation.

**Comment by djkormo** [comment]
WIndows binary version has dwnloaded. I checked and generated sample network policy.  It Works!

**Comment by djkormo** [comment]
Thanks!

**Comment by djkormo** [comment]
I have still the same

kubectl krew install gadget
Updated the local copy of plugin index.
Installing plugin: gadget
W1228 21:43:26.618577    3600 install.go:164] failed to install plugin "gadget": plugin "gadget" does not offer installation for this platform
F1228 21:43:26.636580    3600 root.go:79] failed to install some plugins: [gadget]: plugin "gadget" does not offer installation for this platform
exit status 255
