### ISSUE TITLE
[RFE] gadget/socket-collector: Improve error management if filter matches pods in Error status

### ISSUE THREAD

**Issue by blanquicet** [kinvolk/inspektor-gadget#275]
## Current situation

If there is a pod that goes in Error status, the socket-collector gadgets will fail to run using any filter that matches such pod.

## Impact

For instance, in the following situation, the socket-collector gadget will not work if they filter by `default` namespace and/or `run=mypod` label or even by using `-A` option.

```
$ kubectl get pods --show-labels -n default
NAME        READY   STATUS    RESTARTS   AGE     LABELS
mypod       0/1     Error     0          44m     run=mypod
net         1/1     Running   2          3d20h   app=net
nginx-app   1/1     Running   0          47m     run=nginx-ap
```

It will fail as following:

```
$ kubectl gadget socket-collector -n default
WARN[0002] Error getting traces from node "minikube": failed to retrieve network namespace from PID 26283: no such file or directory  args="[]" command="kubectl-gadget socket-collector"
FATA[0002] Error getting traces from all nodes           args="[]" command="kubectl-gadget socket-collector"
```

## Ideal future situation

Having a couple of pods in error should not block users from tracing anything else.

**Comment by mauriciovasquezbernal** [comment]
@blanquicet do you have an exact reproducer of this issue? 

I tried the following and I wasn't able to reproduce it:

```
# create pod that will go into error 
$ kubectl run mypod --restart=Never --image=praqma/network-multitool -- exit 1

#  create another pod 
kubectl run mypod2 --restart=Never --image=praqma/network-multitool -- sleep 11000

$ kubectl get pods
NAME     READY   STATUS    RESTARTS   AGE
mypod    0/1     Error     0          11m
mypod2   1/1     Running   0          9m23s

# gadget collector works fine 
$ ./kubectl-gadget socket-collector -n default
NODE    NAMESPACE    POD    PROTOCOL    LOCAL    REMOTE    STATUS
```

I think what is happening here is another issue:

1. The list of potential matching containers is gathered in https://github.com/kinvolk/inspektor-gadget/blob/v0.3.0/pkg/gadgets/socket-collector/gadget.go#L71
2. For each of those containers, RunCollector -> https://github.com/kinvolk/inspektor-gadget/blob/v0.3.0/pkg/gadgets/socket-collector/gadget.go#L105
3. Then the netns of the container is inspected -> https://github.com/kinvolk/inspektor-gadget/blob/v0.3.0/pkg/gadgets/socket-collector/tracer/tracer.go#L130. 

If the container is removed between steps 1 & 3, step 3 will fail because the pid for such container doesn't exist anymore. (Actually it's even worst, the pid could have been recycled and be something totally different)...

So I think this can be resolved by:
1. checking if the error returned in [`netnsHandle, err := netns.GetFromPid(int(pid))`](https://github.com/kinvolk/inspektor-gadget/blob/v0.3.0/pkg/gadgets/socket-collector/tracer/tracer.go#L130) is not ENOENT. 

```
if err != nil  {
  if errors.Is(err, syscall.ENOENT) {
   return []socketcollectortypes.Event{}, nil
  }

 return nil, fmt.Errorf....
}
```

2. Somehow check that the PID still corresponds to the pod. Perhaps we could check if the mount namespace id of that PID is the same we have in the gadget container? I think it's not perfect but I don't see better alternatives. @alban do you have any other idea to solve it?

**Comment by blanquicet** [comment]
@mauriciovasquezbernal following the steps to reproduce it. Sorry I didn't describe them from the beginning.

```
# Create pod that will go into error
$ kubectl run mypod-error --restart=Never --image=busybox -- sh -c "sleep 10; exit 1"
pod/mypod-error created

# Ensure pod was detected by gadgettracermanager (Output trimmed)
$ kubectl exec -it $IG -n kube-system -- gadgettracermanager --dump | grep mypod-error
{.. Namespace:default Podname:mypod-error Name:mypod-error ... Pid:77474} 

# Wait more than 10 seconds to ensure it went into Error
$ kubectl get pods -n default
NAME          READY   STATUS   RESTARTS   AGE
mypod-error   0/1     Error    0          3m19s

# Gadget is not working
$ kubectl gadget socket-collector -n default
WARN[0002] Error getting traces from node "ubuntu-focal": failed to retrieve network namespace from PID 77474: no such file or directory  args="[]" command="kubectl-gadget socket-collector"
FATA[0002] Error getting traces from all nodes           args="[]" command="kubectl-gadget socket-collector"

# Clean up things to recover the situation
$ kubectl delete pod mypod-error -n default
pod "mypod-error" deleted

# The error is not anymore there (BTW, I am working to improve this output in another issue)
$ kubectl gadget socket-collector -n default
FATA[0000] Error getting traces from all nodes           args="[]" command="kubectl-gadget socket-collector"
```

The difference with what you are doing is the way you are creating the pod. For some reason, it is not being detected by the gadgettracermanager:

```
# This is how you are creating the pod
$ kubectl run mypod --restart=Never --image=praqma/network-multitool -- exit 1
pod/mypod created

$ kubectl get pods -n default
NAME    READY   STATUS   RESTARTS   AGE
mypod   0/1     Error    0          18s

# Pod is not detected
$ kubectl exec -it $IG -n kube-system -- gadgettracermanager --dump | grep mypod

# Therefore, the gadget will work normally
$ kubectl gadget socket-collector -n default
FATA[0000] Error getting traces from all nodes           args="[]" command="kubectl-gadget socket-collector"
```

My comments:

1. The issue I am reproducing could maybe be solved by discarding containers in Error state from the list returned by https://github.com/kinvolk/inspektor-gadget/blob/v0.3.0/pkg/gadgets/socket-collector/gadget.go#L71? Or more generally, we could remove the container from the list if it is not running? It is still an open discussion. 
2. We should investigate in a different issue why the gadgettracermanager using podinformer (I haven't tried others yet) is not detecting pods if they are created as you are doing.
3. You found indeed a new potential issue and beyond of what we do for this issue, it should be fixed. BTW, great catch! Could you please create another issue?

**Comment by mauriciovasquezbernal** [comment]
I opened https://github.com/kinvolk/inspektor-gadget/issues/314 & https://github.com/kinvolk/inspektor-gadget/issues/315. IMO this issue could be close as IIUC the issue with a pod in error status is due to the pod informer (314) and the new possible race condition is (315). @blanquicet what do you think?

I'm still missing an issue of why podinformer doesn't detect the pod when starting it by `kubectl run mypod-error --restart=Never --image=busybox -- sh -c "exit 1"`, I think this happen that fast that it doesn't have the change to capture the events.

**Comment by blanquicet** [comment]
> What do you think?

I agree. Closing it.
